Slayer/Slayer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^jet/', include('jet.urls', 'jet')),
	url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('main.urls', namespace='main')),
    #url(r'^moderators/', include('moderators.urls', namespace='moderators')),
    url(r'^api/', include('main.urls', namespace='api')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Slayer/api/urls.py
from django.conf.urls import patterns,url
from api.views import auth, game

urlpatterns = [
    url(r'^login/$', auth.login, name='login'),
    url(r'^logout/$', auth.logout, name='logout'),
    url(r'^register/$', auth.register, name='register'),
    url(r'^forgot_password/$', auth.forgot_password, name='forgot_password'),

    url(r'^game/register/$', game.register, name='game_register'),
]

Slayer/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from main.views import auth, profile, process, game
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings	


urlpatterns = [
	url(r'^$', process.basic, name='main_page'),
	url(r'^avatar/', include('avatar.urls')),
	url(r'^login/$', auth.login, name='login'),
	url(r'^logout/$', auth.user_logout, name='logout'),
	url(r'^profile/$', profile.profile, name='profile'),
	url(r'^change_password/$', profile.change_password, name='change_password'),
	url(r'^search/$', profile.search, name='search'),
	url(r'^rating/$', process.rating, name='rating'),
	url(r'^history/$', process.history, name='history'),
	url(r'^kill/$', game.kill, name="kill"),

	url(r'^avatar/', include('avatar.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Slayer/main/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from django.contrib.auth import get_user_model

from main.models import MainUser
from django.forms import ModelForm

User = get_user_model()


class MainUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(MainUserCreationForm, self).__init__(*args, **kwargs)
        #del self.fields['username'] # remove username field that was inherited from AbstractBaseUser

    class Meta(UserCreationForm.Meta):
        model = User
        fields = '__all__'
        exclude = [
        ]


class MainUserChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super(MainUserChangeForm, self).__init__(*args, **kwargs)
        #del self.fields['username'] # remove username field that was inherited from AbstractBaseUser

    class Meta(UserChangeForm.Meta):
        model = User
        fields = '__all__'
        exclude = [
        ]

Slayer/main/views/game.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,get_object_or_404, render_to_response, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, RequestContext
from django.conf import settings
from django.contrib.auth.models import User
from main.models import *
from utils import http, codes, messages

from django.contrib.auth import authenticate, login as auth_login, logout, get_user_model
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_http_methods

from django.views.decorators.csrf import csrf_exempt


import datetime, time

User = get_user_model()


@csrf_exempt
@http.json_response()
@require_http_methods("POST")
@http.required_parameters(["secret_key"])
@login_required
def kill(request):
	"""
	"""

	username = request.user
	
	secret_key = request.POST["secret_key"]

	player = None
	
	print type(username)

	try:
		player = MainUser.objects.get(username="user1")
	except Exception as e:
		print "shit"


	game_entry_1 = None

	try:
		game_entry_1 = GameEntry.objects.get(player=player)
	except Exception as e:
		pass


	victim = game_entry_1.victim
	game_entry_2 = None
	try:
		game_entry_2 = GameEntry.objects.get(player=victim)
	except Exception as e:
		pass

	log = None

	if game_entry_1.secret_key == secret_key:
		log = KillLog.objects.create_log(entry=game_entry_1)
		entry = game_entry_1
		
		game_entry_1.victim = game_entry_2.victim
		game_entry_1.secret_key = game_entry_2.secret_key
		game_entry_1.kills += 1
		game_entry_2.is_active = False
		game_entry_2.save()
		game_entry_1.save()
	else:
		return http.code_response(codes.WRONG_SECRET_KEY, message=messages.WRONG_SECRET_KEY)

	return {
		"result": game_entry_1.to_json()
	}

Slayer/main/views/process.py
# -*- coding: utf-8 -*-

from django.shortcuts import render,get_object_or_404, render_to_response, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, RequestContext
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import messages
# from main.messages import *
from main.models import GameEntry, KillLog, Game

from django.contrib.auth import authenticate, login as auth_login, logout, get_user_model
from django.contrib.auth.decorators import login_required

from django.utils import timezone
from datetime import timedelta
import datetime, time

from avatar.models import Avatar
from utils import string_del
from utils.messages import *

User = get_user_model()


@login_required
def basic(request):
    template = 'main/main.html'
    params = dict()
    params['me'] = request.user
    my_entry = None

    try:
        my_entry = GameEntry.objects.get(player=request.user)
    except Exception as e:
        
        pass
    

    

    if my_entry is not None: 

        victime_entry = None
        try:
            victim_entry = GameEntry.objects.get(player=my_entry.victim)
        except Exception as e:

            pass


        params['my_entry'] = my_entry
        params['secret_key'] = my_entry.secret_key
        params['victim'] = my_entry.victim
        
        params['victim_entry'] = victim_entry
        params['game'] = my_entry.game
        delta = Game.objects.first().start_date - datetime.datetime.now()
        params['game_start_left'] = delta.days * 24 * 60 * 60 +  delta.seconds

        parent_entry = None
        try:
            parent_entry = GameEntry.objects.get(victim=my_entry.player)
        except Exception as e:
            pass

        params['parent_entry'] = parent_entry

        if my_entry.game.status == Game.FINISHED:
            messages.add_message(request, messages.WARNING, GAME_OVER)
            return render(request, template, params)


        if my_entry.player == my_entry.victim:
            params['winner'] = my_entry.player

        elif request.method == "POST":

            victim_entry = get_object_or_404(GameEntry, player=my_entry.victim)

            secret_key = request.POST.get('secret_key')


            if secret_key != "":
                if my_entry.status is GameEntry.KILLED or my_entry.status is GameEntry.DISQUALIFIED:
                    messages.add_message(request, messages.WARNING, YOU_CANNOT_KILL)
                elif secret_key == victim_entry.secret_key:
                    messages.add_message(request, messages.SUCCESS, SUCCESS_KILL)
                    KillLog.objects.create_log(entry=my_entry)
                    victim_entry.status = GameEntry.KILLED
                    victim_entry.save()
                    my_entry.victim = victim_entry.victim
                    my_entry.kills += 1
                    my_entry.save()

                    params['my_entry'] = my_entry
                    params['victim'] = my_entry.victim
                    victim_entry = get_object_or_404(GameEntry, player=my_entry.victim)
                    params['victim_entry'] = victim_entry

                    if my_entry.player == my_entry.victim:
                        params['winner'] = my_entry.player
                else:
                    messages.add_message(request, messages.WARNING, NOT_GOOD_SECRET_KEY)
    else:
        print "blyaat"

    return render(request, template, params)


@login_required
def rating(request):
    template = 'main/rating.html'
    params = dict()
    params['me'] = request.user
    results = list()

    params['total_count'] = GameEntry.objects.filter(player__is_superuser=False).count()
    params['alive_count'] = GameEntry.objects.filter(player__is_superuser=False, status=GameEntry.ALIVE).count()

    # entries = GameEntry.objects.filter(player__is_superuser=False).order_by('status', '-kills')
    params['entries'] = GameEntry.objects.filter(player__is_superuser=False).order_by('status', '-kills', 'player')
    

    return render(request, template, params)


@login_required
def history(request):
    template = 'main/history.html'
    params = dict()
    params['me'] = request.user
    
    results = list()
    params['killer_logs'] = request.user.killer_logs.all()
    print params['killer_logs']

    return render(request, template, params)

Slayer/main/views/profile.py
# -*- coding: utf-8 -*-
from django.shortcuts import render,get_object_or_404, render_to_response, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, RequestContext
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth import authenticate, login as auth_login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from utils.messages import *

User = get_user_model()

import datetime, time

@login_required
def profile(request):

    return render(request, 'main/profile.html')


@login_required
def change_password(request):
    """
    View for changing password
    """
    if request.method == "POST":
        try:
            old_pass = request.POST['old_password']
            new_pass = request.POST['new_password1']
            new_pass1 = request.POST['new_password2']
            if not request.user.check_password(old_pass):
                messages.add_message(request, messages.WARNING, ERROR_OLD_PASS)
                return render(request, 'main/change_password.html')
            if new_pass != new_pass1:
                messages.add_message(request, messages.WARNING, PASSWORDS_DONT_MATCH)
                return render(request, 'main/change_password.html')
            form = PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.add_message(request, messages.SUCCESS, PASSWORD_CHANGED_SUCCESSFULLY)
            else:
                messages.add_message(request, messages.SUCCESS, form.errors)
        except:
            messages.add_message(request, messages.WARNING, ERROR)
    return render(request, 'main/change_password.html')


@login_required
def search(request):
    """
    """
    params = dict()
    template = 'main/search.html'
    if request.method == "POST":
        search_by = request.POST.get('search_by')
        params['users'] = User.objects.filter(Q(username__contains=search_by)|Q(first_name__contains=search_by)| \
     	   Q(second_name__contains=search_by))
        return render(request, template, params)
    return render(request, template)

Slayer/templates/main/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Slayer KBTU</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    {% block head %}

    {% endblock head %}

</head>
<script type="text/javascript">  
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 4000);
</script>

<body >
    <div class="navbar-wrapper">

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo_name" href="{% url 'main:main_page' %}">SLAYER-KBTU</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
        <li><a href="{% url 'main:history' %}">История</a></li>
        <li><a href="{% url 'main:change_password' %}">Сменить пароль</a></li>
      </ul>

      <form class="navbar-form navbar-left" role="search" action="{% url 'main:search' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" class="form-control fc" placeholder="Поиск участников" name="search_by">
            <div class="input-group-btn">
                <button id="toggle-content" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
      </form>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'main:logout' %}">Выйти</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<!--
        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">

              <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'main:main_page' %}">Slayer-KBTU</a></li>
                <li><a href="{% url 'main:rating' %}">Рейтинг</a></li>
                <li><a href="{% url 'main:history' %}">История</a></li>
                <li><a href="{% url 'main:change_password' %}">Сменить пароль</a></li>
              </ul>
            </div>
            <div class="col-sm-3 col-md-3  ">
              <form class="navbar-form" role="search" action="{% url 'main:search' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control fc" placeholder="Search by id or title" name="search_by">
                    <div class="input-group-btn">
                        <button id="toggle-content" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
              </form>
        </div> 
            <div id="navbar" class="navbar-collapse collapse">

              <ul class="nav navbar-nav navbar-right">
                <li><a href="">{{ me.first_name }}</a></li>
                <li><a href="{% url 'main:logout' %}">Выйти</a></li>
              </ul>
            </div>
          </div>
        </nav>
         -->


    </div>



    
      {% if messages %}
    <div class="hidden-messages" >

        {% for message in messages %}
        <p{% if message.tags %} role="alert" class="alert alert-{{ message.tags }} " {% endif %}>{{ message }}</p>
        {% endfor %}
    </div>

    

      {% endif %}

	{% block content %}

  {% endblock content %}
</body>
</html>

Slayer/templates/main/change_password.html
{% extends "main/base.html" %}


{% block head %}
<title>Поменять пароль</title>
{% endblock head %}

{% block content %}
<!-- <div class="container">
	
	<div class="row">
		
		<div class="col-md-4">
			<form action="{% url 'main:change_password' %}" method="post">
				{% csrf_token %}
				
				<div class="row">
					<div class="col-md-6"><label for="old_password" class="form_label">Старый пароль</label></div>
					<div class="col-md-6"><input type="password"  type="password" name="old_password"/></div>
				</div>
				
				<div class="row">
					<div class="col-md-6"><label for="new_password1" class="form_label">Новый пароль</label></div>
					<div class="col-md-6"><input type="password" placeholder="Новый пароль" name="new_password1"/></div>
				</div>

				
				<div class="row">
					<div class="col-md-6"><label for="new_password2" class="form_label">Повторите новый пароль</label></div>
					<div class="col-md-6"><input type="password" placeholder="Повторите новый пароль" name="new_password2"/></div>
				</div>
				

				<button type="submit">Поменять пароль</button>
			</form>
		</div>
	</div>
</div> -->

<div class="container">
	<!-- <div class="row">
		<div class="col-sm-12">
			<h1>Смена пароля</h1>
		</div>		
	</div> -->

	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			
			<form action="{% url 'main:change_password' %}" method="post" id="passwordForm">
				{% csrf_token %}
				
				<input type="password" class="input-md form-control form_input" name="old_password" id="password1" placeholder="Старый пароль" autocomplete="off">

				<input type="password" class="input-md form-control form_input" name="new_password1" id="password1" placeholder="Новый пароль" autocomplete="off">
				
				<input type="password" class="input-md form-control form_input" name="new_password2" id="password2" placeholder="Повторите новый пароль" autocomplete="off">
				
				<input type="submit" class="col-xs-12 btn btn-primary btn-load btn-md" data-loading-text="Changing Password..." value="Поменять пароль">
			</form>
		</div><!--/col-sm-6-->
	</div><!--/row-->
</div>
{% endblock content %}

Slayer/templates/main/history.html
{% extends "main/base.html" %}
{% load avatar_tags %}

{% block head %}
    <title>История убийств</title>
{% endblock head %}

{% block content %}
<div class="container">

    <table class="table table-striped table-hover">
        <th>#</th><th>Аватарка</th><th>Имя</th><th>Факультет</th><th>Статус</th><th>Время убийства</th>
        {% for kill_log in killer_logs %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td><a href="{% avatar_url kill_log.victim 300 %}" >{% avatar kill_log.victim 80 %}</a></td>
            <td>{{kill_log.victim.first_name }} {{ kill_log.victim.second_name}}</td>
        	<td>{% if kill_log.victim.faculty == 0 %} ФИТ
	    	    {% elif kill_log.victim.faculty == 1 %} БШ
                {% elif kill_log.victim.faculty == 2 %} ФЭНГИ
                {% elif kill_log.victim.faculty == 3 %} МШЭ
                {% elif kill_log.victim.faculty == 5 %} КМА
                {% elif kill_log.victim.faculty == 6 %} ХТОВ
                {% elif kill_log.victim.faculty == 7 %} МКМ
                {% elif kill_log.victim.faculty == 8 %} Администрация
                {% else %} Нет информации
                {% endif %}
            </td>
            <td>{% if kill_log.status == 0 %} <span style="color: green">Жив</span>
                {% else %} <span style="color: red">Убит</span>
                {% endif %}</td>
            <td>{{kill_log.timestamp}}</td>
        </tr>
        {% endfor %}
    </table>
            
</div>

{% endblock content %}

Slayer/templates/main/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Slayer.kz</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>   
</head>

<script type="text/javascript">  
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 4000);
</script>

<body>
  

  <div class="loginbg">
     <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
            
                    <div class="account-wall">
                        <div class="avatar">
                            
                        </div> 
                            
                         <form class="form-signin" action="{% url 'main:login' %}" method="post" >
                            {% if messages %}
                              <div class="hidden-messages row login-hidden" >
                                  {% for message in messages %}
                                  <p{% if message.tags %} role="alert" class="alert alert-{{ message.tags }} " {% endif %}>{{ message }}</p>
                                  {% endfor %}
                              </div>
                            {% endif %}

                             <h3 class="form-signin-heading">Slayer-KBTU! <br>Пройдите авторизацию</h3>
              <hr class="colorgraph"><br>
                            {% csrf_token %}
                            <div class="form-group input-group">
                                 <span class="input-group-addon">
                                    <i class="glyphicon glyphicon-envelope "></i></span>
                                        <input  name="username" type="text" class="form-control" placeholder="Username" required autofocus>
                             </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon">
                                    <i class="glyphicon glyphicon-lock "></i></span>
               
                                      <input  name="password" type="password" class="form-control" placeholder="Password" required>
                             </div>
                            <button class="btn btn-lg logbtn btn-block" type="submit">Sign in</button>
                            
                         </form>
                    </div>
           
                </div>
            </div>
        </div>
    </div>
</body>

Slayer/templates/main/rating.html
{% extends "main/base.html" %}
{% load avatar_tags %}


{% block head %}
<title>Рейтинг участников</title>
{% endblock head %}

{% block content %}
<div class="container">

	<table class="table table-striped table-hover">
		<th>#</th><th>Аватар</th><th>ФИО</th><th>Факультет</th><th>Курс</th><th>Убийств</th><th>Статус</th>
    	{% for entry in entries %}
    	<tr>
    		<td>{{forloop.counter}}</td>
	    	<td><a href="{% avatar_url entry.player 300 %}" >{% avatar entry.player 80 %}</a></td>
	    	<td>{{entry.player.first_name }} {{ entry.player.second_name}}</td>
	    	<td>{% if entry.player.faculty == 0 %} ФИТ
                {% elif entry.player.faculty == 1 %} БШ
                {% elif entry.player.faculty == 2 %} ФЭНГИ
                {% elif entry.player.faculty == 3 %} МШЭ
                {% elif entry.player.faculty == 5 %} КМА
                {% elif entry.player.faculty == 6 %} ХТОВ
                {% elif entry.player.faculty == 7 %} МКМ
                {% elif entry.player.faculty == 8 %} Администрация
                {% else %} Нет информации
                {% endif %}
	    	</td>
	    	<td>
	    	   {% if entry.player.course == 1 %} Первый
               {% elif entry.player.course == 2 %} Второй
               {% elif entry.player.course == 3 %} Третий
               {% elif entry.player.course == 4 %} Четвертый
               {% elif entry.player.course == 5 %} Пятый
               {% elif entry.player.course == 6 %} Магистрант
               {% else %} Нет информации
               {% endif %}
                                
	    	</td>
	    	
	    	<td>{{ entry.kills }}</td>
	    	
	    	<td>{% if entry.status == 0 %} 
	    			<span style='color: green'>Жив</span>
	    		{% elif entry.status == 2 %} 
	    			<span style='color: red'>Дисквалифицирован</span>
	    		{% else %} 
	    			<span style='color: red'> Убит </span>
	    		{% endif %}
	    	</td>
	    </tr>
    	{% endfor %}
	</table>

</div>
{% endblock content %}

Slayer/templates/main/search.html
{% extends "main/base.html" %}
{% load avatar_tags %}

{% block content %}
<div class="container">

	<table class="table table-striped table-hover">
		<th>#</th><th>Аватар</th><th>ФИО</th><th>Факультет</th><th>Курс</th>
    	{% for user in users %}
    	<tr>
    		<td>{{forloop.counter}}</td>
	    	<td><a href="{% avatar_url user 300 %}" >{% avatar user 80 %}</a></td>
	    	<td>{{user.first_name }} {{ user.second_name}}</td>
	    	<td>{% if user.faculty == 0 %} ФИТ
                {% elif user.faculty == 1 %} БШ
                {% elif user.faculty == 2 %} ФЭНГИ
                {% elif user.faculty == 3 %} МШЭ
                {% elif user.faculty == 5 %} КМА
                {% elif user.faculty == 6 %} ХТОВ
                {% elif user.faculty == 7 %} МКМ
                {% elif user.faculty == 8 %} Администрация
                {% else %} Нет информации
                {% endif %}
	    	</td>
	    	<td>
	    	   {% if user.course == 1 %} Первый
               {% elif user.course == 2 %} Второй
               {% elif user.course == 3 %} Третий
               {% elif user.course == 4 %} Четвертый
               {% elif user.course == 5 %} Пятый
               {% elif user.course == 6 %} Магистрант
               {% else %} Нет информации
               {% endif %}
	    	</td>
	    </tr>
    	{% endfor %}
	</table>
            
</div>



{% endblock content %}